feat: add hidden documentation about SubscriptionCheckoutComponent
PrestaShopCorp/docs.cloud.prestashop.com pull request #115
Opened 2023-12-21 11:54 UTC by TakeshiDaveau

2024-01-17 09:45 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +In this cas an alias should be added in vite.config.js: `defineViteConfig({ resolve: { alias: { vue: "vue/dist/vue.esm-bundler.js" } } })`.
```suggestion
In this case an alias should be added in vite.config.js: `defineViteConfig({ resolve: { alias: { vue: "vue/dist/vue.esm-bundler.js" } } })`.
```

2024-01-17 09:46 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +    uuid: 'authenticated_user_uUiD',
```suggestion
    uuid: 'authenticated_user_uuid',
```

2024-01-17 09:47 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +Please ask us to know the value to provide as `product.id` and `offerSelection.offerPricingId`.
```suggestion
If you do not know what value to provide for the `product.id` and the`offerSelection.offerPricingId`, don't hesitate to ask us.
```

2024-01-17 09:48 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +Please do not use the event hook to register the fact a customer has subscribe to your product. It's not safe. Prefer the [webhook mechanism](../../6-references/1-webhook/).
```suggestion
Please do not use the event hook to register the fact a customer has subscribed to your product. It's not safe. Prefer the [webhook mechanism](../../6-references/1-webhook/).
```

2024-01-17 09:50 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +#### Vue 3
issue: pour les deux use-cases, je mettrais un rappel de comment ajouter les hooks sur l'initialization

2024-01-17 09:51 UTC, maximesimoncelli requested changes
Quelques suggestions + une précision à apporter

2024-01-17 13:33 UTC, maximesimoncelli commented on docs/src/5-prestashop-billing/100-hidden/1-checkout-subscription/README.md
> +#### Vue 3
Yep nickel

2024-01-17 13:33 UTC, maximesimoncelli approved these changes

2024-01-18 08:26 UTC, khanhmas approved these changes

2024-01-18 09:04 UTC, jmcollin approved these changes

2024-02-20 07:56 UTC, merged